USE [master]
GO
/****** Object:  Database [M4TP1_SUIVI_REPAS]    Script Date: 12/11/2021 11:01:15 ******/
CREATE DATABASE [M4TP1_SUIVI_REPAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'M4TP1_SUIVI_REPAS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\M4TP1_SUIVI_REPAS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'M4TP1_SUIVI_REPAS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\M4TP1_SUIVI_REPAS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [M4TP1_SUIVI_REPAS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET ARITHABORT OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET  DISABLE_BROKER 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET RECOVERY FULL 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET  MULTI_USER 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'M4TP1_SUIVI_REPAS', N'ON'
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET QUERY_STORE = OFF
GO
USE [M4TP1_SUIVI_REPAS]
GO
/****** Object:  User [userSuiviRepas]    Script Date: 12/11/2021 11:01:15 ******/
CREATE USER [userSuiviRepas] FOR LOGIN [userSuiviRepas] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [userSuiviRepas]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [userSuiviRepas]
GO
/****** Object:  Table [dbo].[ALIMENTS]    Script Date: 12/11/2021 11:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALIMENTS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nom] [varchar](50) NOT NULL,
	[id_repas] [int] NOT NULL,
 CONSTRAINT [PK_ALIMENTS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REPAS]    Script Date: 12/11/2021 11:01:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPAS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[date_repas] [date] NOT NULL,
	[heure_repas] [time](7) NOT NULL,
 CONSTRAINT [PK_REPAS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ALIMENTS]  WITH CHECK ADD  CONSTRAINT [FK_ALIMENTS_REPAS] FOREIGN KEY([id_repas])
REFERENCES [dbo].[REPAS] ([id])
GO
ALTER TABLE [dbo].[ALIMENTS] CHECK CONSTRAINT [FK_ALIMENTS_REPAS]
GO
USE [master]
GO
ALTER DATABASE [M4TP1_SUIVI_REPAS] SET  READ_WRITE 
GO
