USE [master]
GO
/****** Object:  Database [M9TP1_NOTES]    Script Date: 17/11/2021 20:34:25 ******/
CREATE DATABASE [M9TP1_NOTES]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'M9TP1_NOTES', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\M9TP1_NOTES.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'M9TP1_NOTES_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\M9TP1_NOTES_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [M9TP1_NOTES] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [M9TP1_NOTES].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [M9TP1_NOTES] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET ARITHABORT OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [M9TP1_NOTES] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [M9TP1_NOTES] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET  DISABLE_BROKER 
GO
ALTER DATABASE [M9TP1_NOTES] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [M9TP1_NOTES] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET RECOVERY FULL 
GO
ALTER DATABASE [M9TP1_NOTES] SET  MULTI_USER 
GO
ALTER DATABASE [M9TP1_NOTES] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [M9TP1_NOTES] SET DB_CHAINING OFF 
GO
ALTER DATABASE [M9TP1_NOTES] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [M9TP1_NOTES] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [M9TP1_NOTES] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'M9TP1_NOTES', N'ON'
GO
ALTER DATABASE [M9TP1_NOTES] SET QUERY_STORE = OFF
GO
USE [M9TP1_NOTES]
GO
/****** Object:  User [userNotes]    Script Date: 17/11/2021 20:34:25 ******/
CREATE USER [userNotes] FOR LOGIN [userNotes] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [userNotes]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [userNotes]
GO
/****** Object:  Table [dbo].[Notes]    Script Date: 17/11/2021 20:34:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Notes](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[contenu] [varchar](500) NOT NULL,
	[date] [datetime] NOT NULL,
 CONSTRAINT [pk_notes] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [M9TP1_NOTES] SET  READ_WRITE 
GO
INSERT INTO Notes(contenu, date) VALUES ('Acheter des croquettes pour machine', GETDATE());
INSERT INTO Notes(contenu, date) VALUES ('Soirée bière le 20/02 à 20h02', GETDATE());
INSERT INTO Notes(contenu, date) VALUES ('Anniversaire de ta tante tati', GETDATE());
INSERT INTO Notes(contenu, date) VALUES ('Entretient avec un banquier!', GETDATE());