USE [master]
GO
/****** Object:  Database [FORMATIONJ2E]    Script Date: 12/11/2021 10:18:47 ******/
CREATE DATABASE [FORMATIONJ2E]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FORMATIONJ2E', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FORMATIONJ2E.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FORMATIONJ2E_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\FORMATIONJ2E_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [FORMATIONJ2E] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FORMATIONJ2E].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FORMATIONJ2E] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET ARITHABORT OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FORMATIONJ2E] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FORMATIONJ2E] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FORMATIONJ2E] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FORMATIONJ2E] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET RECOVERY FULL 
GO
ALTER DATABASE [FORMATIONJ2E] SET  MULTI_USER 
GO
ALTER DATABASE [FORMATIONJ2E] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FORMATIONJ2E] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FORMATIONJ2E] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FORMATIONJ2E] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FORMATIONJ2E] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'FORMATIONJ2E', N'ON'
GO
ALTER DATABASE [FORMATIONJ2E] SET QUERY_STORE = OFF
GO
USE [FORMATIONJ2E]
GO
/****** Object:  User [utilisateurBDD]    Script Date: 12/11/2021 10:18:47 ******/
CREATE USER [utilisateurBDD] FOR LOGIN [utilisateurBDD] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [utilisateurBDD]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [utilisateurBDD]
GO
/****** Object:  Table [dbo].[AVIS]    Script Date: 12/11/2021 10:18:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AVIS](
	[identifiant] [int] IDENTITY(1,1) NOT NULL,
	[description] [varchar](150) NOT NULL,
	[note] [tinyint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AVIS]  WITH CHECK ADD  CONSTRAINT [CK_AVIS] CHECK  (([note]>=(1) AND [note]<=(5)))
GO
ALTER TABLE [dbo].[AVIS] CHECK CONSTRAINT [CK_AVIS]
GO
USE [master]
GO
ALTER DATABASE [FORMATIONJ2E] SET  READ_WRITE 
GO
