USE [master]
GO
/****** Object:  Database [M5TP1_LISTES_COURSE]    Script Date: 16/11/2021 15:16:44 ******/
CREATE DATABASE [M5TP1_LISTES_COURSE]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'M5TP1_LISTES_COURSE', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\M5TP1_LISTES_COURSE.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'M5TP1_LISTES_COURSE_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\M5TP1_LISTES_COURSE_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [M5TP1_LISTES_COURSE].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET ARITHABORT OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET  DISABLE_BROKER 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET RECOVERY FULL 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET  MULTI_USER 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET DB_CHAINING OFF 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'M5TP1_LISTES_COURSE', N'ON'
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET QUERY_STORE = OFF
GO
USE [M5TP1_LISTES_COURSE]
GO
/****** Object:  User [userListesCourse]    Script Date: 16/11/2021 15:16:44 ******/
CREATE USER [userListesCourse] FOR LOGIN [userListesCourse] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[ARTICLES]    Script Date: 16/11/2021 15:16:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ARTICLES](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nom] [varchar](50) NOT NULL,
	[id_liste] [int] NOT NULL,
	[coche] [bit] NULL,
 CONSTRAINT [PK_ARTICLES] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LISTES]    Script Date: 16/11/2021 15:16:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LISTES](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nom] [varchar](50) NOT NULL,
 CONSTRAINT [PK_LISTES] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ARTICLES] ADD  DEFAULT ((0)) FOR [coche]
GO
USE [master]
GO
ALTER DATABASE [M5TP1_LISTES_COURSE] SET  READ_WRITE 
GO
